name: Tests

on:
  push:

jobs:
  setup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Pest ${{ matrix.test-suite }} on PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: ['8.3']
        test-suite: ['phpcsfixer', 'phpstan', 'rector', 'phpcs']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Test php code
        run: vendor/bin/pest -p --testsuite ${{ matrix.test-suite }}
