name: Static Analysis

on: [push]

jobs:
  ecs:
    name: ECS

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --ansi

      - name: Style
        run: composer test:lint
